---
- name: download source code
  git: repo=https://github.com/rebar/rebar.git
       dest={{ rebar_download_dir }}
       version={{ rebar_version }}
       update=no

- name: compile rebar using the bootstrap script
  command: ./bootstrap
  args:
    chdir: "{{ rebar_download_dir }}"
    creates: rebar

- name: copy script into user's bin directory
  copy: src={{ rebar_download_dir }}/rebar
        dest={{ rebar_bin }}
        mode=0777
  sudo: yes
