---
- name: install dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items:
    - git
  sudo: yes
  when: ansible_os_family == "Debian"

- name: install dependencies
  yum: name={{ item }} state=present
  with_items:
    - git
  sudo: yes
  when: ansible_os_family == "RedHat"

- include: install.yml
  when: rebar_install_from_source == false

- include: install_from_source.yml
  when: rebar_install_from_source == true
